--------------------------------------------------------
--  DDL for Table ECB_USER_DETAIL
--------------------------------------------------------

  CREATE TABLE "ECB_USER_DETAIL" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(100 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"ADDRESS1" VARCHAR2(100 BYTE), 
	"ADDRESS2" VARCHAR2(100 BYTE), 
	"CITY" VARCHAR2(100 BYTE), 
	"STATE" VARCHAR2(100 BYTE), 
	"ZIP" VARCHAR2(100 BYTE), 
	"USER_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Sequence ECB_USER_DETAIL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ECB_USER_DETAIL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER  NOCYCLE ;
INSERT INTO ECB_USER_DETAIL (ID,NAME,PHONE,EMAIL,ADDRESS1,ADDRESS2,CITY,STATE,ZIP,USER_ID) 
VALUES (1,"Zihao","2023554567","luckzh94@gmail.com","5 Independency way","suite 140","Princeton","NJ","08540",1);
--------------------------------------------------------
--  DDL for Index ECB_USER_DETAIL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECB_USER_DETAIL_PK" ON "ECB_USER_DETAIL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

--------------------------------------------------------
--  DDL for Trigger ECB_USER_DETAIL_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ECB_USER_DETAIL_TRG" 
BEFORE INSERT ON ECB_USER_DETAIL 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT ECB_USER_DETAIL_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ECB_USER_DETAIL_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table ECB_USER_DETAIL
--------------------------------------------------------

  ALTER TABLE "ECB_USER_DETAIL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ECB_USER_DETAIL" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "ECB_USER_DETAIL" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "ECB_USER_DETAIL" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "ECB_USER_DETAIL" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ECB_USER_DETAIL" MODIFY ("STATE" NOT NULL ENABLE);
  ALTER TABLE "ECB_USER_DETAIL" MODIFY ("ZIP" NOT NULL ENABLE);
  ALTER TABLE "ECB_USER_DETAIL" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ECB_USER_DETAIL" ADD CONSTRAINT "ECB_USER_DETAIL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;