--------------------------------------------------------
--  File created - Sat-Oct-27-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ECB_SHELVES
--------------------------------------------------------

  CREATE TABLE "ECB_SHELVES" 
   (	"ID" NUMBER, 
	"ON_SHELVES_DATE" DATE DEFAULT SYSDATE NOT NULL,
    "USER_ID" NUMBER,
    "TYPE" VARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
--------------------------------------------------------
--  DDL for Sequence ECB_SHELVES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ECB_SHELVES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER  NOCYCLE ;
Insert into ECB_SHELVES (ID,USER_ID,TYPE) values (1,1,'AUNCTION');
Insert into ECB_SHELVES (ID,USER_ID,TYPE) values (2,1,'SELL');

--------------------------------------------------------
--  DDL for Index ECB_SHELVES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECB_SHELVES_PK" ON "ECB_SHELVES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

--------------------------------------------------------
--  DDL for Trigger ECB_SHELVES_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ECB_SHELVES_TRG" 
BEFORE INSERT ON ECB_SHELVES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT ECB_SHELVES_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/
ALTER TRIGGER "ECB_SHELVES_TRG" ENABLE;

--------------------------------------------------------
--  Constraints for Table ECB_SHELVES
--------------------------------------------------------

  ALTER TABLE "ECB_SHELVES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ECB_SHELVES" ADD CONSTRAINT "ECB_SHELVES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;