--------------------------------------------------------
--  File created - Sat-Oct-27-2018  
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ECB_PRODUCT
--------------------------------------------------------

  CREATE TABLE "ECB_PRODUCT" 
   (	"ID" NUMBER, 
	"TITLE" VARCHAR2(255 BYTE),
    "DESCRIPTION" VARCHAR2(1000),
    "TYPE_ID" NUMBER, 
	"PRICE" NUMBER, 
	"DEADLINE" DATE, 
	"IMAGE" BLOB,
    "SHELVES_DATE" DATE DEFAULT SYSDATE NOT NULL,
    "SALE_DATE" DATE    
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
--------------------------------------------------------
--  DDL for Sequence ECB_PRODUCT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ECB_PRODUCT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
REM INSERTING into ECB_PRODUCT
SET DEFINE OFF;
Insert into ECB_PRODUCT (ID,TITLE,DESCRIPTION,TYPE_ID,PRICE,DEADLINE,IMAGE) 
values (1,'New iPhoneXS is saling','very new very new very new very new',1,888,TO_DATE('2018/11/25 10:31:22', 'yyyy/mm/dd hh24:mi:ss'),null);
--Insert into ECB_PRODUCT (ID,NAME,BRAND,PRICE,STOCK,IMAGE) values (2,'Water','Costco',20,200,null);
--Insert into ECB_PRODUCT (ID,NAME,BRAND,PRICE,STOCK,IMAGE) values (3,'Milk','Wholefoods',30,300,null);
--------------------------------------------------------
--  DDL for Index PRODUCT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ECB_PRODUCT_PK" ON "ECB_PRODUCT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger ECB_PRODUCT_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ECB_PRODUCT_TRG" 
BEFORE INSERT ON ECB_PRODUCT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT ECB_PRODUCT_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ECB_PRODUCT_TRG" ENABLE;

--------------------------------------------------------
--  Constraints for Table ECB_PRODUCT
--------------------------------------------------------

  ALTER TABLE "ECB_PRODUCT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ECB_PRODUCT" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "ECB_PRODUCT" MODIFY ("TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "ECB_PRODUCT" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "ECB_PRODUCT" MODIFY ("DEADLINE" NOT NULL ENABLE);
  ALTER TABLE "ECB_PRODUCT" ADD CONSTRAINT "ECB_PRODUCT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;